[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"

[[build.hooks.post_build]]
command = "cp frontend/public/index-seo.html frontend/build/index.html"
