export default {
  header: {
    navTool: "Herramienta",
    navExamples: "Ejemplos",
    navFairHousing: "Vivienda Justa",
    navPresentation: "Presentación",
    navBlog: "Blog",
    navPricing: "Precios",
    tryFree: "Prueba Gratis →",
    esToggle: "🇪🇸 ES",
    enToggle: "🇺🇸 EN",
  },
  common: {
    loading: "Cargando…",
    error: "Algo salió mal. Intenta de nuevo.",
    copied: "¡Copiado!",
    copy: "Copiar",
    close: "Cerrar",
    preview: "Vista previa",
    noCard: "Sin tarjeta",
    cancelAnytime: "cancela cuando quieras",
    moneyBack30: "Garantía de 30 días",
    billedUSD: "facturado en USD",
    tryFree: "Prueba Gratis — Sin Tarjeta",
    learnMore: "Saber Más →",
    previewAll: "Ver Todas las Páginas →",
  },
  hero: {
    est: "EST. 2026 — COPY INMOBILIARIO, REESCRITO",
    headline1: "ChatGPT escribe",
    headline2: "violaciones de Vivienda Justa por $26,262.",
    headline3: "Nosotros las detectamos.",
    subtitle: "Un pegado → copia para MLS, revisión de Vivienda Justa, caption de Instagram, 5 titulares, email para compradores. 10 segundos. cero riesgo normativo.",
    subtitle2: "Escribe tu listado en 60 segundos en vez de una hora. Prueba el playground gratis. Sin tarjeta. Ve la diferencia tú mismo.",
    formats: ["Descripción MLS", "Caption Instagram", "Publicación Facebook", "5 Titulares", "Email Comprador"],
    formatsTag: "— un solo clic.",
    fhPlaceholder: "Pega tu listado aquí",
    fhExample: 'Ejemplo: "Perfecto para familias con niños. Vecindario seguro y tranquilo cerca de las mejores escuelas."',
    fhMinChars: "Mín. 20 caracteres",
    fhCheck: "Revisar violaciones",
    fhChecking: "Revisando…",
    fhFree: "✦ 100% gratis",
    fhNoAccount: "● Sin cuenta",
    fh5Sec: "● 5 segundos",
    fhClean: "Sin violaciones encontradas",
    fhCleanMsg: "Tu listado pasó la revisión de Vivienda Justa.",
    fhRewrite: "Reescribir con IA ahora",
    fhCheckAnother: "Revisar otro",
    fhViolations: "{count} violación(es) — riesgo {risk}",
    fhIssues: "Este listado tiene problemas de Vivienda Justa.",
    fhFix: "Corregir con IA — Prueba Gratis",
    fhError: "Algo salió mal. Intenta de nuevo.",
    bullets: [
      "✦ Acceso ilimitado al playground",
      "● Sin tarjeta de crédito",
      "● 10s por listado",
      "● Revisión de Vivienda Justa",
    ],
  },
  playground: {
    sectionLabel: "/ La Herramienta",
    heading: "Tu listado aburrido.",
    heading2: "Cinco activos listos para publicar.",
    inputLabel: "Entrada · Listado Crudo",
    useSample: "Usar ejemplo →",
    placeholder: "Pega tu borrador de MLS aquí. Entre más detalles, mejor el resultado.",
    tone: "Tono",
    tones: ["Lujo", "Acogedor", "Moderno", "Minimalista", "Familiar", "Inversionista"],
    outputLang: "Idioma de Salida",
    mlsLimit: "Límite de Caracteres MLS",
    mlsPresets: [
      "Sin límite / Predeterminado",
      "Bright MLS — 350 palabras",
      "CRMLS — 400 palabras",
      "GAMLS — 350 palabras",
      "Stellar MLS — 300 palabras",
      "MRED — 350 palabras",
      "REcolorado — 350 palabras",
      "Metrolist — 400 palabras",
      "ACTRIS — 300 palabras",
      "Personalizado — 250 palabras",
      "Personalizado — 500 palabras",
    ],
    startFree: "Empieza Gratis — Reescribe Este Listado",
    rewrite: "Reescribir Mi Listado",
    rewriting: "Reescribiendo…",
    freeNote: "3 reescrituras gratis, luego $29/mes · cancela cuando quieras",
    awaiting: "Esperando entrada",
    awaitingMsg: "Tu listado reescrito aparecerá aquí.",
    awaitingHint: "Pega un borrador, elige un tono, presiona reescribir. Cinco activos listos en unos 10 segundos.",
    generating: "Generando",
    copyCrush: "Copiar y Publicar",
    copied: "Copiado",
    share: "Compartir",
    strength: "Fuerza {score}/10",
    proTip: "Consejo: Lee esto directo a la cámara de tu teléfono. Sin teleprompter.",
    tabs: {
      mls: "Descripción MLS",
      instagram: "Instagram",
      facebook: "Facebook",
      headlines: "Titulares",
      email: "Email",
      reel: "Guion Reel",
      stories: "Historias",
      flyer: "Volante Impreso",
    },
    proUpsell: "ListWorks PRO",
    proUpsellMsg: "Reescrituras ilimitadas · videos sin marca de agua · el Asesor IA en tu bolsillo.",
    getPro: "Obtén Pro — $29/mes",
    tools: {
      revrite: "Reesritur a Listado",
      staging: "Ambientación Virtua",
      bio: "Biografía del Agente",
      photo: "Foto → Listado",
      agentpag: "ágna delAgente",
      cma: "Infrome ACM",
      brandvoice: "Voz de la Marca",
      referral: "Refiere y Gana",
      batch: "CSV por Lote",
      expired: "Guiones para Vencidos",
      import: "Importar URL",
      seller: "Informes para Vendedores",
      nurture: "Nutrición de Leads",
      score: "Puntuación de Leads",
      transaction: "Transacciones",
      openhouse: "Casa Abierta",
      fairhousing: "Vivienda Justa",
      coat: "Divulgaciónde IA",
      voice: "Camina y Habla",
      report: "Informe de Venta",
      templates: "Plantillas Sociales",
      calendar: "Calendario de Contenido",
      marketupdate: "Actualización de Mercado",
      scheduler: "Programar Publicaciones",
    },
    meta: {
      address: "Dirección (opconal)",
      price: "Precio",
      beds: "Camas",
      baths: "Baños",
      sqft: "pies2",,
      vitualTour: "Recorrido Itual 360°",
      virtualTourPlaceholder: "https://mymatterport.com/show/?m=...",
    },
    gems: {
      buton: "Ver Escuelas · Restaurantes · Vecindario →",
      loading: "Obteniendo datos de vecindario…",
      heading: "Datos delBarrio",
      add: "Agregar a i listado →",
      added: "Contxto del vecindario añadido tu listado.",    },
    ookup: {
      buton: "Llenar atoático · baños · pies2 →",
      loading: "Bucando…",
      success: "Dtails de la proiedad rellendaos atomaticamente.",
      notFound: "No e encontraron datosúblicos — llna nualmente.",
    },
  },
  proof: {
    sectionLabel: "/ Comprobantes",
    headline: "El mismo listado. Su vecindario, escrito.",
    before: "Antes",
    beforeSub: "Borrador genérico",
    after: "Después / ListWorks",
    afterSub: "+ Inteligencia dle Vecindari — auto-agregado",
    strength: "Fuerza del Litsdo",
    strengtScore: "{scor}/10",
    stronger: "+{prcent}% má fuere",
    rewrite: "Reescribe lute

    reeCTA: "3 reesritura grati · Sin taejta de créido · Ve la difeenci en 10 seundos",
    examplesLabel: "/ Ejemplos Completos",
    examplesTitle: "Pruébalos en el playgound.",
    examplesCTA: "Prueba tu direcció →",
neighborhood: "Inteligencia del Vecindario",
    neighborhoodSub: "Pruébalo con cualuier dirección dE UU.",
    neighborhoodPlaceholder: "Empieza a escribir una dirección...",,
    neighborhoodFetch: "Buscar",
    neighorhoodSchools: "Escelas",
    neighbrhoodDining: "Restaurantes",
    neighbohoodTransit: "Transporte",
    neighborhooodEmpt: "aparecá quí",
    neighborhoddAdd: "Agregar a mi listado",
    geoloading: "Obteniendo escuelas, restaurantes y datos de tránsito…",
  },resentation: {
    sectonLabel: "/ Gana Más Listados",
    heading: "55 Páginas"    heading2: "Presentación e Venta",
    subtitle: "Plantil lenabla. Hoj de trbao ACM, calcuaora denaqueo neto, caledario de mretng, pánas decumpimiento normativo. Funcona en t navegador — sin softwae.",
    buy: "Comprar Plantial — $27",
    cover: "Portada",
    cma: "Hoja de Traajo ACM",
    netProceeds: "Ingreo Neto",
    mktgCalndar: "Caledario de Marketing"
    sections: "36 Seccones Rellenabls",,
    guarantee: "Descarga nmediata · HTML + PDF dieabl · Acualizacones gatis · Garanía de 0 día",
  },
  pricing: {
    sectionLabel: "/ Precios",
    headline: "Empieza gratis. Escala sin ímites.",
    flatRat: "Un sola traifa pla",
    noLimts: "Sn ímites de créito",
    unlimited: "Reescrituras ilimitadas",
    free: {
      name: "Gratis",
      price: "$0",
      period: "siepre",
      desc: "Paa agentes que uieren proarlo sn su próxim listado.",
      features: [
        "Aces ilimitado al pleyround",
        "Tods los 5 formtos de salida",
        "6 mmdos de to",
        "Revisión de Vvienda Juta",
        "Ve los resultaos ntes de guadar",
      ],
      cta: "Empezar Gratis",
    },
    pro: {
      tag: "Recomenado",
      nae: "Lista + io",
      price: "$29",
      perid: "/mes",
      desc: "Reescrituras ilimitadas sin ansiedad de créditos. Copia para listados + tu marca de agente — todo en una tarifa plana.",
      features: [
        "Reescrituras de listados ilimitadas",
        "31 plantillas sociales con tu voz de marca",
        "Generador de calendario de contenido de 30 días",
        "Generador de actualización de mercado en vivo",
        "Programador de publicaciones con recordatorios por email",
        "Importación de URL de cualquier listado (Zillow, Redfin, MLS…)",,
        "Reisón de Vivienda Justa + PDF de cumlimiento CO Act",
        "Geerador e Biograía del Aente (3 formatos)",,
        "Vídeos sin marca de agua",
        "Historial de listados (para siempre)",
      ],
      cta: "Obtén Lista + Bio — $29/mes",
    },
    lifetime: {
      tag: "MEJOR VLO",
      nme: "Duraión de Vida",
      prce "$299",
      period: "una vez"
      desc: "Miembro fundador — paga una vez, nunca vuelvas a pagar.",
      features: [
        "Todo lo de Pro",
        "Acceso para siempre (sin mensualidad)",
        "Todas las funciones futuras incluidas",
        "Soporte prioritario",
        "Insignia de miembro fundador",
        "Recorridos en video con IA",
        "Generación prioritaria de videos",
      ],
      cta: "Asegura Vitalicio — $299",
    },
    credits: {
      label: "/ Créditos — paga sobre la marcha",
      note: "· Cada crédito = una reescritura completa · nunca caduvan",
      10: {
        qty: "10 Créditos",
        price: "$5",
        desc: "10 reescrituras de IA — sin vencimiento.",
        badge: "Paga sobre la marcha",
      },
      50: {
        qty: "50 Créditos",
        price: "$19",
        desc: "50 reescrituras de IA — el mejor valor sobre la marcha.",
        badge: "Ahora 24%",
      },
    },
    brokerage: "¿Necesitas 10+ asientos? Habla con ventas para corretajes →",
  },
  faq: {
    sectionLabel: "/ Preguntas Frecuentes",
    headline: "Las preguntas que siempre nos hacen.",
    email: "¿No ves la tuya? Envía un email a hello@listworks.pro",
    items: [
      {
        q: "¿Esto son solo plantillas?",
        a: "No. ListWorks es un sistema envuelto en una herramienta. Aprendes POR QUÉ funciona cada pieza — luego la IA lo aplica a cada listado en tu voz. Las plantillas copian. Los sistemas se acumulan.",
      },
      {
        q: "¿Tengo que usar IA?",
        a: "No. La guía de $20 enseña el sistema completo para que puedas escribir mejor copia a mano. La herramienta de IA solo lo hace 27 minutos más rápido por listado.",
      },
      {
        q: "¿Va a sonar como ChatGPT?",
        a: "Para nada. Los resultados genéricos de ChatGPT son mediocres porque están entrenados con todos los listados de internet — incluidos los malos. ListWorks está ajustado con el sistema Característica → Beneficio → Sentimiento que los agentes del 1% superior realmente usan.",
      },
      {
        q: "¿Y si no me gusta?",
        a: "Garantía de devolución de 30 días en la guía. El playground de la herramienta es completamente gratis con acceso ilimitado — pruébalo tantas veces como quieras antes de decidir actualizar.",
      },
      {
        q: "¿Es compatible con MLS?",
        a: "Sí. Los resultados evitan trampas de vivienda justa, hipérboles y afirmaciones no verificables por defecto. Siempre revisa antes de publicar — como con cualquier borrador.",
      },
      {
        q: "¿Puede usarlo toda mi corretaje?",
        a: "Sí — el plan Equipo incluye 5 asientos, bibliotecas de listados compartidas y ajustes de voz específicos para la corretaje. Envía un email a hello@listworks.pro para una demostración.",
      },
      {
        q: "¿En qué se diferencia de ChatGPT?",
        a: "ChatGPT te da texto inmobiliario genérico porque está entrenado con todo internet. ListWorks está entrenado con el sistema Característica → Beneficio → Sentimiento — el mismo que usan los agentes del 1% superior para cerrar. Un solo prompt, cero relleno.",
      },
      {
        q: "¿Las publicaciones de Instagram y Facebook realmente funcionan?",
        a: "Sí. Más de 200 agentes las usan semanalmente. Jessica Martinez (LA) cerró 2 listados en menos de una semana con publicaciones generadas aquí. Priya Nair (Chicago) dice que sus DMs de IG se triplicaron. Los captions están diseñados para detener el desplazamiento, no para la vanidad.",
      },
    ],
  },
  footer: {
    tagline: "Copia inmobiliaria, reescrita.",
    desc: "Creado para agentes que prefieren vender casas que mirar formularios de MLS. Prueba la herramienta gratis. Lee la guía una vez. Úsala para siempre.",
    product: "Producto",
    productLinks: ["La Herramienta", "Ejemplos", "Blog", "Herramientas Gratis", "Estadísticas de Mercado", "Comparar", "Precios"],
    compliance: "Cumplimiento",
    complianceLinks: ["Guía de Vivienda Justa", "Guías de los 50 Estados", "Divulgación de IA CO", "Analizador de Listados"],
    earn: "Gana",
    earnLinks: ["Hazte Afiliado", "Panel de Afiliados", "Contacto"],
    company: "Empresa",
    companyLinks: ["Privacidad", "Términos"],
    newsletter: "Boletín",
    newsletterDesc: "Una carta / mes. El sistema, refinado. Sin spam.",
    newsletterPlaceholder: "agente@corretaje.com",
    copyright: "© 2026 ListWorks PRO · Hecho para agentes",
  },
  video: {
    sectionLabel: "/ Motor de Video",
    demo: "Demo en vivo",
    headline1: "Diez fotos.",
    headline2: "Un reel cinematográfico",
    headline3: "listo.",
    desc: "Sin software de edición. Sin horas extra. Solo sube las fotos de tu listado — la IA escribe el guion, elige la música y renderiza un recorrido de 30 segundos listo para Instagram, Facebook y tu campaña de email.",
    inputLabel: "ENTRADA — 10 FOTOS CRUDAS"
    outputLabel: "RERNDIZADO EN 8 SGUNDOS",
    overlay: "Gnerad por IA · emo de 30 s",
    makeReel: "Hacer Mi Reel de Listado",
    seePlans: "Ver planes →",
    stats: [
      { value: "10", label: "Fotos" },
      { valule: "30s", label: "Duración Fna" },
      { value: "1080p", lable: "Calidad MP4" },
      { value: "9:16", label: "Fomato Rels (Pro)" },
    ],
  },
  contentEngine: {
    sectionLabel: "/ Paquete de Salida",
    headline: "Una entrada. Seis salidas listas para publicar.",
    tabs: ["Guion e Reel", "Caption Instagrm", "Carrue de 6 Diápositivas", "Calendario de 7 Días", "Informe de Mercado", "Plantillas Canva"],
    reel: {
      hook: "Gancho (0–3s)",
      middle: "Desarlo (3–2s)",
      close: "Cierre (12–15s)",
    },
  },
  qr: {
    sectionLabel: "/ Herramientas QR",
    headline: "Cada listado se convierte en un punto de captura de leads.",
    signQr: "QR para el Letrero",
    signSub: "Cada letrero = u imán de eads",
    openHouse: "Registro ara Casa Aierta",
    openSub: "Contatos autoapturados",
    feedback: "Retroalimentación de la Visita",
    feedbackSub: "Retroalimentación + lead en una sola lectura",
    seeWhat: "Haz clic para ver lo que ven los compradores →",
    collapse: "Haz clic para colapsar ↑",
    footer: "Sin necesidad de instalar app · Funciona en cualquier teléfono · Cada lectura capturada en tu panel",
  },
  contracts: {
    sectionLabel: "/ Contratos",
    headline: "Contratos que se explican solos.",
    desc: "Cada campo en cada contrato tiene una explicación en español claro. No más adivinar qué significa 'comisión del corredor cooperante'.",
    tryFree: "Pruébalo Gratis →",
    noCard: "Sin tarjeta de crédito · Reescrituras gatis incluidas",
    list: [
      "Contrato de Listado — 14 campos, cada uno explicado",
      "Contrato de Compra — precio, contingencias, cierre, todo desglosado",
      "Divulgación del Vendedor — techo, HVAC, daños por agua, obligaciones legales",
      "Contrato de Arrendamiento — renta, depósito, mascotas, subarriendo, todo cubierto",
      "Contrato de Representación del Comprador — compensación, plazo, territorio",
    ],
  },
  dashboard: {
    sectionLabel: "/ Panel",
    headline: "Todo detrás de un solo inicio de sesión.",
    tabs: ["Generador", "Paquetes de Contenido", "Contratos", "Marca"],
    open: "Abrir Panel →",
    freeNote: "Cuenta gratis · Primeras 3 reescrituras incluidas · Sin tarjeta de crédito",
  },};